# Configuration for the rawr CLI tool
target_json_path: /Users/mateicanavra/Library/Application Support/Cursor/User/globalStorage/rooveterinaryinc.roo-cline/settings/custom_modes.json # Path to the target JSON file storing agent configs
markdown_base_dir: agents/ # Base directory containing agent Markdown definition folders